/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Multicall } from "./Multicall";
export type { UniversalErc20 } from "./UniversalErc20";
export * as factories from "./factories";
export { Multicall__factory } from "./factories/Multicall__factory";
export { UniversalErc20__factory } from "./factories/UniversalErc20__factory";
